-- AlterTable
ALTER TABLE "Logs_Permissions" ALTER COLUMN "idAdministrador_mod" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "idUsuario" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "Permiso" SET DATA TYPE VARCHAR(100);
